Repository lje00220/PINGER, pull requests merged in 2025-03, with the labels that each got.

#32 Feat: 로그인 기능 구현 + Auth 클라이언트 상태 구축
  index.html
  src/App.jsx
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/layout/Nav.jsx
  src/constants/toastMessages.js
  src/hooks/useAuthListener.js
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/zustand/useAuthStore.js
Labels: ✨ Feature, 📬 API, 🐻 민경

#34 Refactor: resume card 공통 컴포넌트 제작
  src/api/bookMarks.js
  src/components/common/JobItem.jsx
  src/components/common/ResumeItem.jsx
  src/components/features/myPage/Profile.jsx
  src/components/features/myPage/ResumeList.jsx
Labels: 🔨 Refactor, 🐣 민조

#36 Feature/map search 검색 기능 및 오버레이 수정
  src/components/maps/BasicMap.jsx
  src/components/maps/JobOverlay.jsx
  src/zustand/useMapStore.js
Labels: ✨ Feature, 🎨 HTML&CSS, 🏡 효진

#38 Feat: 채용공고 디테일 페이지 댓글 CRUD 구현
  package.json
  pnpm-lock.yaml
  src/api/reviews.js
  src/components/common/LoadingPage.jsx
  src/components/features/jobDetail/JobComment.jsx
  src/components/features/jobDetail/JobCommentTable.jsx
  src/constants/queryKeys.js
  src/hooks/useReviewsQuery.js
  src/pages/JobDetail.jsx
Labels: ✨ Feature, 📬 API, 🍜 지은

#42 HTML/CSS: Login/Signup 페이지 스타일링 + Feat: Nav에 유저 정보 표시
  index.html
  pnpm-lock.yaml
  public/images/PINGER_favi.png
  public/images/PINGER_logo.png
  public/vite.svg
  src/App.jsx
  src/components/auth/AuthForm.jsx
  src/components/auth/SignupAddressInput.jsx
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/layout/Header.jsx
  src/components/layout/Nav.jsx
  src/index.css
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/utils/validate.js
  tailwind.config.js
Labels: ✨ Feature, 🐞 BugFix, 🎨 HTML&CSS, 🐻 민경

#45 Bugfix: Button 컴포넌트 hover 문제 해결
  src/index.css
Labels: 🐞 BugFix, 🎨 HTML&CSS, 🐻 민경

#46 Style/map searchbar maker / 지도, 마커, 검색창 수정
  public/images/PINGER_marker.png
  src/components/maps/BasicMap.jsx
  src/components/maps/JobOverlay.jsx
  src/constants/inputPlaceholder.js
  src/hooks/useKakaoLoader.js
Labels: ✨ Feature, 🎨 HTML&CSS, 🏡 효진

#47 feat: 댓글 수정에 낙관적 업데이트 적용
  src/api/reviews.js
  src/components/features/jobDetail/JobComment.jsx
  src/components/features/jobDetail/JobCommentTable.jsx
  src/hooks/useReviewsQuery.js
  src/pages/JobDetail.jsx
  src/pages/JobListPage.jsx
Labels: ✨ Feature, 🐞 BugFix, 🍜 지은

#48 Feat: 사용자 정보 수정하기 기능 추가 및 마이페이지 UI 수정
  src/api/bookMarks.js
  src/api/users.js
  src/components/common/JobItem.jsx
  src/components/features/myPage/BookMarkList.jsx
  src/components/features/myPage/Profile.jsx
  src/constants/queryKeys.js
  src/constants/toastMessages.js
  src/hooks/bookmarks/useAddBookmarkMutation.js
  src/hooks/bookmarks/useDeleteBookmarkMutation.js
  src/hooks/useBookMarksQuery.js
  src/hooks/users/useUpdateUserMutation.js
  src/pages/MyPage.jsx
  src/pages/Signup.jsx
  src/utils/toggleBookMark.js
Labels: ✨ Feature, 🐣 민조

#58 Feat: 멘토 페이지 구현
  src/api/resumes.js
  src/components/common/JobItem.jsx
  src/components/common/ResumeItem.jsx
  src/components/features/myPage/BookMarkList.jsx
  src/components/features/myPage/ResumeList.jsx
  src/hooks/bookmarks/useBookMarksQuery.js
  src/hooks/useResumeQuery.js
  src/pages/MyPage.jsx
Labels: ✨ Feature, 📬 API, 🐣 민조

#60 Refactor/map component (#8) 맵관련 코드 리팩토링
  src/components/MapContainer.jsx
  src/components/maps/BasicMap.jsx
  src/components/maps/JobMarkers.jsx
  src/components/maps/JobOverlay.jsx
  src/components/maps/MapControls.jsx
  src/components/maps/MapMarkers.jsx
  src/components/maps/SearchPanel.jsx
  src/components/maps/SearchResults.jsx
  src/constants/regionCoordinates.js
  src/hooks/map/useMapCenter.js
  src/hooks/map/useMapEffects.js
  src/hooks/map/useMapHandlers.js
  src/hooks/useJobsQuery.js
  src/hooks/useKakaoLoader.js
  src/pages/Home.jsx
  src/pages/JobDetail.jsx
  src/pages/JobListPage.jsx
  src/pages/MyPage.jsx
  src/zustand/map/mapUtils.js
  src/zustand/map/useMapActions.js
  src/zustand/map/useMapState.js
  src/zustand/useMapStore.js
Labels: ✨ Feature, 🔨 Refactor, 🏡 효진

#62 Feat: 닉네임 수정 시에 중복 닉네임 방지 처리
  src/api/bookMarks.js
  src/api/fetchData.js
  src/components/common/JobItem.jsx
  src/components/features/myPage/BookMarkList.jsx
  src/components/features/myPage/Profile.jsx
  src/utils/validate.js
Labels: ✨ Feature, 📬 API, 🐣 민조

#63 Feat : 채용리스트 무한 스크롤
  src/api/fetchData.js
  src/api/resumes.js
  src/components/common/JobItem.jsx
  src/components/features/Resume/ResumeForm.jsx
  src/components/maps/BasicMap.jsx
  src/constants/inputPlaceholder.js
  src/constants/mode.js
  src/constants/queryKeys.js
  src/hooks/useJobsQuery.js
  src/pages/JobListPage.jsx
  src/pages/ResumeDetail.jsx
  src/pages/ResumeListPage.jsx
Labels: ✨ Feature, 🔨 Refactor, 🚘 종욱

#64 [Refactor] 북마크 데이터 조회 로직 리팩토링
  src/api/bookMarks.js
  src/components/auth/AuthForm.jsx
  src/components/common/JobItem.jsx
  src/components/features/myPage/BookMarkList.jsx
  src/components/layout/Nav.jsx
  src/hooks/bookmarks/useBookMarksQuery.js
  src/hooks/bookmarks/useDeleteBookmarkMutation.js
  src/pages/JobDetail.jsx
  src/pages/MyPage.jsx
Labels: 🔨 Refactor, 📬 API, 🐣 민조

#65 Feat: 인트로 모달 추가
  package.json
  pnpm-lock.yaml
  src/components/MapContainer.jsx
  src/components/common/IntroModal.jsx
  src/components/maps/BasicMap.jsx
  src/pages/Home.jsx
  src/pages/JobDetail.jsx
  src/zustand/useMapStore.js
  src/zustand/useModalStore.js
Labels: ✨ Feature, 🔨 Refactor, 🍜 지은

#68 bugfix: 회원가입 오류 해결
  src/components/auth/AuthForm.jsx
  src/pages/Signup.jsx
Labels: 🐞 BugFix, 🐻 민경
