Repository lje00220/PINGER, pull requests merged in 2025-02, with the labels that each got.

#10 feat: supabase api 통신 함수 구현
  src/api/deleteData.js
  src/api/fetchData.js
  src/api/insertOrUpdate.js
  src/pages/Home.jsx
  src/supabase/client.js
  src/zustand/useAuthStore.js
Labels: 📬 API

#12 feat: react-icons 라이브러리 추가 및 MyPage 프로필 UI 구현
  package.json
  pnpm-lock.yaml
  src/components/common/JobItem.jsx
  src/components/features/myPage/BookMarkList.jsx
  src/components/features/myPage/Profile.jsx
  src/pages/MyPage.jsx
Labels: 🎨 HTML&CSS, 🐣 민조

#13 feat: 공공데이터 전체 마크, 따옴표수정, query 생성 #8
  src/api/fetchData.js
  src/components/maps/BasicMap.jsx
  src/hooks/useJobsQuerys.js
  src/main.jsx
  src/service/supabase.js
Labels: ✨ Feature, 📬 API, 🏡 효진

#19 feat: 채용 공고 디테일 페이지 레이아웃
  src/components/jobList/JobLIstItem.jsx
  src/pages/JobDetail.jsx
  src/pages/JobListPage.jsx
  src/utils/SliceTitleLength.js
Labels: ✨ Feature, 🎨 HTML&CSS, 🍜 지은

#20 Feature/login
  src/components/common/Button.jsx
  src/components/common/Input.jsx
  src/components/maps/BasicMap.jsx
  src/hooks/useForm.js
  src/pages/Login.jsx
  src/pages/Signup.jsx
  tailwind.config.js
Labels: ✨ Feature, 📬 API, 🐻 민경

#22 Style: 채용정보 카드 width 적용 수정
  src/components/common/JobItem.jsx
  src/pages/JobListPage.jsx
Labels: 🎨 HTML&CSS, 🐣 민조

#24 Feature/map zoom in out 줌인아웃 및 검색기능
  src/components/maps/BasicMap.jsx
Labels: ✨ Feature, 📬 API, 🏡 효진

#27 feat + refactor: 회원가입 로직 리팩토링 및 사용자 주소 추가 기능 구현
  src/App.jsx
  src/components/auth/AuthForm.jsx
  src/components/auth/SignupAddressInput.jsx
  src/components/common/Button.jsx
  src/components/common/ErrorText.jsx
  src/components/common/Input.jsx
  src/constants/inputPlaceholder.js
  src/constants/mode.js
  src/constants/toastMessages.js
  src/hooks/useForm.js
  src/index.css
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/utils/validate.js
Labels: ✨ Feature, 🔨 Refactor, 🐻 민경

#28 Refactor: 마이페이지 로직 수정 + 파일명 수정 및 경로 수정
  src/api/bookMarks.js
  src/api/createData.js
  src/api/deleteData.js
  src/api/fetchData.js
  src/components/common/JobInfo.jsx
  src/components/common/JobItem.jsx
  src/components/features/myPage/BookMarkList.jsx
  src/components/features/myPage/Profile.jsx
  src/components/features/myPage/ResumeList.jsx
  src/components/layout/Header.jsx
  src/components/layout/Nav.jsx
  src/constants/dateRange.js
  src/constants/iconSize.js
  src/constants/queryKeys.js
  src/constants/routerPath.js
  src/hooks/useBookMarksQuery.js
  src/hooks/useJobsQuerys.js
  src/pages/JobDetail.jsx
  src/pages/MyPage.jsx
  src/pages/ResumeListPage.jsx
  src/shared/Router.jsx
  src/utils/handleToggleBookMark.js
  src/utils/toggleBookMark.js
Labels: 🔨 Refactor, 🐣 민조
